/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/bubble.glb 
*/

import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'

export function BubbleModel() {
  const { nodes, materials } = useGLTF('/bubble.glb')
  return (
    <group dispose={null} rotation={[0, -Math.PI / 2, 0]}>
      <mesh geometry={(nodes.Plane as Mesh).geometry} material={materials.cartoon} />
    </group>
  )
}

useGLTF.preload('/bubble.glb')
